# Generated by Django 3.2.12 on 2022-06-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-date'], 'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolio Profiles'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
