# Generated by Django 3.2.12 on 2022-04-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['name'], 'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolio Profiles'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='quote',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
