# Generated by Django 3.2.12 on 2022-06-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220607_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
