# Generated by Django 3.2.12 on 2022-06-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_portfolio_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='link',
            field=models.CharField(blank=True, default='devsearch111.herokuapp.com', max_length=100),
        ),
    ]
